return {
    useMPH = false,
    outMap = false,
    hud = {
        hideThreshold = 90,
        blinkThreshold = 15,
    },
    voiceVolumes = { 1.5, 3, 6 },
    hudColors = {
        primary = '#f5881b',
        lowEngine = '#bc1b1b',
        ui = {
            primary = '#f5881b',
            buttonHover = '#e07a16',
            editingBg = 'rgba(245, 136, 27, 0.2)',
            minimapBg = 'rgba(245, 136, 27, 0.15)',
            minimapBorder = '#f5881b',
        },
        stats = {
            health = { '#ff4d4d', '#8e1212' },
            hunger = { '#ffcc5c', '#90551d' },
            thirst = { '#4d79a8', '#1e4a89' },
            armor = { '#9b9917', '#5d5b1a' },
            oxygen = { '#4bafb6', '#1f8a91' },
            stress = { '#c974ff', '#7f2bd8' },
        },
        vehicle = {
            fuel = '#f5881b',
            engineGood = '#27ae60',
            engineBad = '#e74c3c',
        },
    },
    stress = {
        enableStress = true,
        chance = 0.1,
        minForShaking = 50,
        minForSpeeding = 1000,
        minForSpeedingUnbuckled = 50,
        whitelistedWeapons = {
            `weapon_petrolcan`,
            `weapon_hazardcan`,
            `weapon_fireextinguisher`,
        },
        blurIntensity = {
            [1] = { min = 50, max = 60, intensity = 1500 },
            [2] = { min = 60, max = 70, intensity = 2000 },
            [3] = { min = 70, max = 80, intensity = 2500 },
            [4] = { min = 80, max = 90, intensity = 2700 },
            [5] = { min = 90, max = 100, intensity = 3000 },
        },
        effectIntervalRange = {
            [1] = { min = 50, max = 60, minTimeout = 50000, maxTimeout = 60000 },
            [2] = { min = 60, max = 70, minTimeout = 40000, maxTimeout = 50000 },
            [3] = { min = 70, max = 80, minTimeout = 30000, maxTimeout = 40000 },
            [4] = { min = 80, max = 90, minTimeout = 20000, maxTimeout = 30000 },
            [5] = { min = 90, max = 100, minTimeout = 15000, maxTimeout = 20000 },
        },
    },
    weaponsArmedMode = {
        `weapon_petrolcan`,
        `weapon_hazardcan`,
        `weapon_fireextinguisher`,
        `weapon_dagger`,
        `weapon_bat`,
        `weapon_bottle`,
        `weapon_crowbar`,
        `weapon_flashlight`,
        `weapon_golfclub`,
        `weapon_hammer`,
        `weapon_hatchet`,
        `weapon_knuckle`,
        `weapon_knife`,
        `weapon_machete`,
        `weapon_switchblade`,
        `weapon_nightstick`,
        `weapon_wrench`,
        `weapon_battleaxe`,
        `weapon_poolcue`,
        `weapon_briefcase`,
        `weapon_briefcase_02`,
        `weapon_garbagebag`,
        `weapon_handcuffs`,
        `weapon_bread`,
        `weapon_stone_hatchet`,
        `weapon_grenade`,
        `weapon_bzgas`,
        `weapon_molotov`,
        `weapon_stickybomb`,
        `weapon_proxmine`,
        `weapon_snowball`,
        `weapon_pipebomb`,
        `weapon_ball`,
        `weapon_smokegrenade`,
        `weapon_flare`,
    },
    customHudStats = {
        [1] = {
            name = 'car',
            icon = 'fa-solid fa-car',
            border = '#00ff00',
            fill = '#2da42d',
        }
    },
}